import { MERCHANT_PATTERNS, CATEGORIES, resolveTransactionCategory } from './types.js';

/**
 * Universal CSV Parser that handles:
 * - UTF-8 BOM (\uFEFF)
 * - Quoted values and commas/delimiters inside quotes
 * - Variable delimiters (comma, semicolon, tab)
 * - Bank statement title/metadata header rows before table
 * - Summary/footer rows at the end of statements
 */
export function parseRawCSV(csvText) {
  if (!csvText || typeof csvText !== 'string' || !csvText.trim()) {
    throw new Error('CSV content is empty');
  }

  // 1. Strip UTF-8 BOM and normalize line breaks
  const cleanText = csvText.replace(/^\uFEFF/, '').trim();

  // 2. Auto-detect delimiter from non-empty sample lines
  const sampleLines = cleanText.split(/\r?\n/).filter(l => l.trim().length > 0).slice(0, 5);
  let delimiter = ',';
  if (sampleLines.length > 0) {
    const commaCount = (sampleLines[0].match(/,/g) || []).length;
    const semiCount = (sampleLines[0].match(/;/g) || []).length;
    const tabCount = (sampleLines[0].match(/\t/g) || []).length;
    if (semiCount > commaCount && semiCount > tabCount) delimiter = ';';
    else if (tabCount > commaCount && tabCount > semiCount) delimiter = '\t';
  }

  // 3. Robust token parsing with quotes handling
  const lines = [];
  let row = [];
  let currentToken = '';
  let inQuotes = false;

  for (let i = 0; i < cleanText.length; i++) {
    const char = cleanText[i];
    const nextChar = cleanText[i + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        currentToken += '"';
        i++; // skip escaped quote
      } else {
        inQuotes = !inQuotes;
      }
    } else if (char === delimiter && !inQuotes) {
      row.push(currentToken.trim());
      currentToken = '';
    } else if ((char === '\r' || char === '\n') && !inQuotes) {
      if (char === '\r' && nextChar === '\n') {
        i++; // skip \n of \r\n
      }
      row.push(currentToken.trim());
      currentToken = '';
      if (row.some(cell => cell.length > 0)) {
        lines.push(row);
      }
      row = [];
    } else {
      currentToken += char;
    }
  }

  if (currentToken.length > 0 || row.length > 0) {
    row.push(currentToken.trim());
    if (row.some(cell => cell.length > 0)) {
      lines.push(row);
    }
  }

  if (lines.length < 2) {
    throw new Error('CSV must contain a header row and at least one transaction row');
  }

  // 4. Locate actual table header row (skips bank account metadata lines)
  let headerLineIndex = 0;
  for (let i = 0; i < Math.min(15, lines.length); i++) {
    const lineStr = lines[i].join(' ').toLowerCase();
    const hasDate = /date|time|txn/.test(lineStr);
    const hasMoney = /amount|debit|credit|withdrawal|deposit|balance|spent|inr|paid|received/.test(lineStr);
    const hasDesc = /desc|narration|particular|detail|remark|merchant|memo/.test(lineStr);

    if ((hasDate && hasMoney) || (hasDate && hasDesc) || (hasMoney && hasDesc)) {
      headerLineIndex = i;
      break;
    }
  }

  const rawHeaders = lines[headerLineIndex];
  const headers = rawHeaders.map((h, idx) => {
    const clean = h.replace(/^["']|["']$/g, '').trim();
    return clean || `Column_${idx + 1}`;
  });

  // 5. Extract rows, ignoring footer / summary rows
  const rawRows = lines.slice(headerLineIndex + 1);
  const rows = [];

  for (const r of rawRows) {
    if (!r || r.length === 0 || r.every(cell => !cell || cell.trim().length === 0)) continue;
    const firstCell = String(r[0] || '').toLowerCase().trim();
    const rowStr = r.join(' ').toLowerCase();

    // Skip summary / page / total lines
    if (/^(total|grand total|subtotal|closing balance|opening balance as on|generated by|end of statement|page \d+)/i.test(firstCell) ||
        /^(total|grand total|subtotal)/i.test(rowStr)) {
      continue;
    }

    const obj = {};
    headers.forEach((h, idx) => {
      obj[h] = r[idx] !== undefined ? r[idx] : '';
    });
    rows.push(obj);
  }

  return { headers, rows, format: 'csv' };
}

/**
 * Universal JSON Parser for transaction statements
 */
export function parseRawJSON(jsonText) {
  if (!jsonText || typeof jsonText !== 'string' || !jsonText.trim()) {
    throw new Error('JSON content is empty');
  }

  const cleanText = jsonText.replace(/^\uFEFF/, '').trim();
  const parsed = JSON.parse(cleanText);
  let arrayData = [];

  if (Array.isArray(parsed)) {
    arrayData = parsed;
  } else if (parsed && typeof parsed === 'object') {
    if (Array.isArray(parsed.transactions)) {
      arrayData = parsed.transactions;
    } else if (Array.isArray(parsed.data)) {
      arrayData = parsed.data;
    } else if (Array.isArray(parsed.statement)) {
      arrayData = parsed.statement;
    } else {
      const arrKey = Object.keys(parsed).find(k => Array.isArray(parsed[k]));
      if (arrKey) {
        arrayData = parsed[arrKey];
      } else {
        throw new Error('JSON must contain an array of transaction records');
      }
    }
  }

  if (arrayData.length === 0) {
    throw new Error('No transactions found in JSON file');
  }

  const headerSet = new Set();
  arrayData.forEach(item => {
    if (item && typeof item === 'object') {
      Object.keys(item).forEach(k => headerSet.add(k));
    }
  });

  const headers = Array.from(headerSet);
  const rows = arrayData.map(item => {
    const obj = {};
    headers.forEach(h => {
      obj[h] = item[h] !== undefined ? item[h] : '';
    });
    return obj;
  });

  return { headers, rows, format: 'json' };
}

/**
 * Auto-detects statement format (CSV or JSON) and parses
 */
export function detectAndParseStatement(rawContent) {
  const trimmed = (rawContent || '').replace(/^\uFEFF/, '').trim();
  if (trimmed.startsWith('[') || trimmed.startsWith('{')) {
    try {
      return parseRawJSON(trimmed);
    } catch {
      return parseRawCSV(trimmed);
    }
  }
  return parseRawCSV(trimmed);
}

/**
 * Heuristics to auto-detect best column mappings from arbitrary headers
 */
export function autoDetectMappings(headers = []) {
  const mapping = {
    date: '',
    description: '',
    amount: '',
    type: '',
    merchant: '',
    category: '',
    withdrawal: '',
    deposit: ''
  };

  const lowerHeaders = headers.map(h => ({ 
    raw: h, 
    lower: String(h || '').toLowerCase().replace(/[^a-z0-9]/g, '') 
  }));

  // Date
  const dateMatch = lowerHeaders.find(h => /date|time|txndate|transdate|posteddate|valuedate/.test(h.lower));
  if (dateMatch) mapping.date = dateMatch.raw;

  // Description / Narration
  const descMatch = lowerHeaders.find(h => /narration|particular|desc|detail|remark|memo|title|note/.test(h.lower));
  if (descMatch) mapping.description = descMatch.raw;

  // Withdrawal / Debit Column
  const withdrawMatch = lowerHeaders.find(h => /withdrawal|debit|outflow|dr|spent|debitamt|withdrawalamt/.test(h.lower));
  if (withdrawMatch) mapping.withdrawal = withdrawMatch.raw;

  // Deposit / Credit Column
  const depositMatch = lowerHeaders.find(h => /deposit|credit|inflow|cr|received|creditamt|depositamt/.test(h.lower));
  if (depositMatch) mapping.deposit = depositMatch.raw;

  // Amount
  const amtMatch = lowerHeaders.find(h => /amount|amt|netamount|total|price|inr|val/.test(h.lower) && !/debit|credit|withdrawal|deposit/.test(h.lower));
  if (amtMatch) {
    mapping.amount = amtMatch.raw;
  } else if (mapping.withdrawal) {
    mapping.amount = mapping.withdrawal;
  } else if (mapping.deposit) {
    mapping.amount = mapping.deposit;
  }

  // Type (Debit/Credit or Income/Expense)
  const typeMatch = lowerHeaders.find(h => /type|drcr|trxtype|crdr|categorytype|flow/.test(h.lower));
  if (typeMatch) mapping.type = typeMatch.raw;

  // Merchant
  const merchMatch = lowerHeaders.find(h => /merchant|payee|beneficiary|vendor|store|counterparty|channel/.test(h.lower));
  if (merchMatch) mapping.merchant = merchMatch.raw;

  // Category
  const catMatch = lowerHeaders.find(h => /cat|category|tag|group|classification/.test(h.lower));
  if (catMatch) mapping.category = catMatch.raw;

  if (!mapping.merchant && mapping.description) {
    mapping.merchant = mapping.description;
  }

  return mapping;
}

/**
 * Checks if a narration represents an Opening / Closing balance snapshot rather than an expense
 */
export function isBalanceSnapshotNarration(text = '') {
  const str = String(text || '');
  return /opening\s*bal|balance\s*b\/f|balance\s*brought\s*forward|available\s*(today|balance)|opening\s*balance|ledger\s*bal|closing\s*bal|starting\s*(account\s*)?balance|initial\s*(account\s*)?balance/i.test(str);
}

/**
 * Cleans messy Indian bank narrations and extracts recognizable merchant names & payment channels
 */
export function cleanIndianNarration(rawNarration = '') {
  const text = (rawNarration !== undefined && rawNarration !== null ? String(rawNarration) : '').trim();
  if (!text) return { cleanedDescription: 'Transaction', cleanedMerchant: 'Store', paymentMethod: 'UPI' };

  let paymentMethod = 'UPI';
  let cleanedMerchant = text;

  // Detect payment channel
  if (/atm|cash\s*wdl|atm-cash/i.test(text)) {
    paymentMethod = 'ATM Cash Withdrawal';
  } else if (/neft|rtgs/i.test(text)) {
    paymentMethod = 'NEFT/RTGS Bank Transfer';
  } else if (/imps/i.test(text)) {
    paymentMethod = 'IMPS Direct Deposit';
  } else if (/mandate|nach|auto-debit|e-mandate/i.test(text)) {
    paymentMethod = 'Auto-Debit e-Mandate';
  } else if (/pos|card|visa|mastercard|rupay/i.test(text)) {
    paymentMethod = 'Debit Card POS';
  } else if (/upi|@ok|@paytm|@ybl|@axl|@icici/i.test(text)) {
    const handleMatch = text.match(/@([a-zA-Z0-9]+)/);
    paymentMethod = handleMatch ? `UPI @${handleMatch[1]}` : 'UPI';
  }

  // Extract clean merchant name from common Indian SMS/Bank format
  const upiParts = text.split(/[/|-]/).map(s => s.trim()).filter(Boolean);
  if (upiParts.length >= 3) {
    const foundWord = upiParts.find(p => p.length > 2 && !/^\d+$/.test(p) && !/^(upi|cr|dr|rev|pos|txn|inr|sms)$/i.test(p));
    if (foundWord) {
      cleanedMerchant = foundWord.charAt(0).toUpperCase() + foundWord.slice(1).toLowerCase();
    }
  }

  // Format known merchant names cleanly
  const knownMerchants = [
    'Swiggy', 'Zomato', 'Blinkit', 'Zepto', 'Instamart', 'Uber', 'Ola', 'Rapido', 
    'Netflix', 'Spotify', 'Amazon', 'Flipkart', 'Apollo Pharmacy', 'Airtel', 'Jio', 
    'Cult.fit', 'Hotstar', 'BookMyShow', 'SBI ATM', 'HDFC Bank ATM', 'TCS', 'Infosys', 
    'Razorpay', 'Papa', 'Mummy', 'Living Liquidz', 'Tonique', 'Madhushala', 'Tasmac', 'Theka', 'Toit', 'Beer Cafe'
  ];

  for (const km of knownMerchants) {
    if (new RegExp(km, 'i').test(text)) {
      cleanedMerchant = km;
      break;
    }
  }

  return {
    cleanedDescription: text,
    cleanedMerchant,
    paymentMethod
  };
}

/**
 * Robust date parser supporting Indian formats:
 * - DD/MM/YYYY, DD-MM-YYYY, DD.MM.YYYY
 * - DD-Mon-YYYY (22-Sep-2025)
 * - YYYY-MM-DD
 * - Timestamps (22/09/2025 14:30:00)
 */
export function parseAnyDate(rawDateInput) {
  if (!rawDateInput) return new Date().toISOString().split('T')[0];
  const str = String(rawDateInput).trim();
  if (!str) return new Date().toISOString().split('T')[0];

  // Strip timestamp part
  const dateOnly = str.split(/[T\s]/)[0].trim();

  // Pattern 1: ISO YYYY-MM-DD
  const isoMatch = dateOnly.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/);
  if (isoMatch) {
    return `${isoMatch[1]}-${isoMatch[2].padStart(2, '0')}-${isoMatch[3].padStart(2, '0')}`;
  }

  // Pattern 2: DD-Mon-YYYY (e.g. 22-Sep-2025 or 22/Sep/2025)
  const monthNames = {
    jan: '01', feb: '02', mar: '03', apr: '04', may: '05', jun: '06',
    jul: '07', aug: '08', sep: '09', oct: '10', nov: '11', dec: '12'
  };
  const monMatch = dateOnly.match(/^(\d{1,2})[-/\s]([a-zA-Z]{3,9})[-/\s](\d{2,4})$/);
  if (monMatch) {
    const day = monMatch[1].padStart(2, '0');
    const monKey = monMatch[2].slice(0, 3).toLowerCase();
    const month = monthNames[monKey] || '01';
    const year = monMatch[3].length === 2 ? `20${monMatch[3]}` : monMatch[3];
    return `${year}-${month}-${day}`;
  }

  // Pattern 3: Indian format DD/MM/YYYY or DD-MM-YYYY
  const dmyMatch = dateOnly.match(/^(\d{1,2})[-/.](\d{1,2})[-/.](\d{2,4})$/);
  if (dmyMatch) {
    let day = parseInt(dmyMatch[1], 10);
    let month = parseInt(dmyMatch[2], 10);
    let year = dmyMatch[3].length === 2 ? `20${dmyMatch[3]}` : dmyMatch[3];

    if (day > 12 && month <= 12) {
      // standard DD/MM/YYYY
    } else if (month > 12 && day <= 12) {
      const temp = day;
      day = month;
      month = temp;
    }
    return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
  }

  // Fallback to JS Date
  const d = new Date(str);
  if (!isNaN(d.getTime())) {
    return d.toISOString().split('T')[0];
  }

  return new Date().toISOString().split('T')[0];
}

/**
 * Intelligent categorizer & metadata inferrer with confidence score
 */
export function inferCategoryAndType(description = '', merchant = '', inputType = '', amount = 0) {
  const text = `${description} ${merchant}`.toLowerCase();

  // Pattern search
  for (const item of MERCHANT_PATTERNS) {
    if (item.match.test(text)) {
      return {
        category: item.category || 'Other',
        type: item.type || (amount < 0 ? 'expense' : 'income'),
        recurring: !!item.recurring,
        essential: !!item.essential,
        confidence: 0.96,
        isBalanceSnapshot: !!item.isBalanceSnapshot
      };
    }
  }

  // Type inference fallback
  let inferredType = 'expense';
  if (inputType) {
    const lowerType = String(inputType).toLowerCase();
    if (/cr|credit|income|inflow|deposit/.test(lowerType)) {
      inferredType = 'income';
    } else if (/transfer|xfer/.test(lowerType)) {
      inferredType = 'transfer';
    }
  } else if (amount > 0 && /salary|stipend|freelance|bonus|received|credit|from papa|from mom|allowance/i.test(text)) {
    inferredType = 'income';
  }

  let inferredCategory = inferredType === 'income' ? 'Salary' : 'Other';

  return {
    category: inferredCategory,
    type: inferredType,
    recurring: false,
    essential: false,
    confidence: 0.70,
    isBalanceSnapshot: isBalanceSnapshotNarration(text)
  };
}

/**
 * Normalizes, repairs incomplete data, and validates mapped statement rows
 */
export function validateAndNormalizeCSVRows(rows, mapping, existingTransactions = []) {
  const seenInBatch = new Set();
  let detectedOpeningBalance = null;

  const normalizedRows = (rows || []).map((rawRow, index) => {
    const errors = [];
    const warnings = [];
    let autoRepaired = false;

    // 1. Date Validation & Normalization
    const rawDateVal = mapping.date ? rawRow[mapping.date] : '';
    let parsedDate = parseAnyDate(rawDateVal);
    if (!rawDateVal) {
      warnings.push('Incomplete data: Missing date assigned to today');
      autoRepaired = true;
    }

    // 2. Amount Validation & Clean Parsing
    let parsedAmount = 0;
    let inferredTypeFromSign = 'expense';

    const cleanNum = (val) => {
      if (val === undefined || val === null || val === '') return NaN;
      const str = String(val).replace(/,/g, '').replace(/[^0-9.-]/g, '');
      const parsed = parseFloat(str);
      return isNaN(parsed) ? NaN : parsed;
    };

    const rawWithdrawalStr = mapping.withdrawal ? rawRow[mapping.withdrawal] : '';
    const rawDepositStr = mapping.deposit ? rawRow[mapping.deposit] : '';
    const rawAmountStr = mapping.amount ? rawRow[mapping.amount] : '';

    const numWithdrawal = cleanNum(rawWithdrawalStr);
    const numDeposit = cleanNum(rawDepositStr);
    const numAmount = cleanNum(rawAmountStr);

    if (!isNaN(numWithdrawal) && numWithdrawal > 0) {
      parsedAmount = Math.abs(numWithdrawal);
      inferredTypeFromSign = 'expense';
    } else if (!isNaN(numDeposit) && numDeposit > 0) {
      parsedAmount = Math.abs(numDeposit);
      inferredTypeFromSign = 'income';
    } else if (!isNaN(numAmount) && numAmount !== 0) {
      if (numAmount < 0) {
        parsedAmount = Math.abs(numAmount);
        inferredTypeFromSign = 'expense';
      } else {
        parsedAmount = Math.abs(numAmount);
        const amtStr = String(rawAmountStr).toLowerCase();
        if (/dr|debit|outflow/.test(amtStr)) {
          inferredTypeFromSign = 'expense';
        } else if (/cr|credit|inflow|deposit/.test(amtStr)) {
          inferredTypeFromSign = 'income';
        }
      }
    } else {
      errors.push(`Invalid or zero amount`);
      parsedAmount = 0;
    }

    // 3. Description & Merchant Cleaning
    const rawDesc = String(
      (mapping.description ? rawRow[mapping.description] : '') || 
      (mapping.merchant ? rawRow[mapping.merchant] : '') || 
      `Transaction #${index + 1}`
    ).trim();

    const { cleanedDescription, cleanedMerchant, paymentMethod } = cleanIndianNarration(rawDesc);
    const merchant = String(mapping.merchant && rawRow[mapping.merchant] ? rawRow[mapping.merchant] : cleanedMerchant).trim();

    // Check if row is an Opening Balance snapshot
    const isSnapshot = isBalanceSnapshotNarration(rawDesc) || isBalanceSnapshotNarration(merchant);
    if (isSnapshot && parsedAmount > 0) {
      detectedOpeningBalance = parsedAmount;
      warnings.push(`Opening balance detected (₹${parsedAmount.toLocaleString('en-IN')}). Sets account starting cash, NOT an expense!`);
    }

    // 4. Type Validation
    let rawType = mapping.type ? String(rawRow[mapping.type] || '').trim() : '';
    let normalizedType = isSnapshot ? 'balance_snapshot' : inferredTypeFromSign;
    if (rawType && !isSnapshot) {
      const lower = rawType.toLowerCase();
      if (/cr|credit|income|deposit|inflow/.test(lower)) {
        normalizedType = 'income';
      } else if (/dr|debit|expense|withdrawal|outflow/.test(lower)) {
        normalizedType = 'expense';
      } else if (/transfer|xfer|split/.test(lower)) {
        normalizedType = 'transfer';
      }
    }

    // 5. Inferred category
    const categoryFromRow = mapping.category ? rawRow[mapping.category] : '';
    const categoryInfo = inferCategoryAndType(cleanedDescription, merchant, normalizedType, parsedAmount);
    const directCatKey = categoryFromRow ? Object.keys(CATEGORIES).find(k => k.toLowerCase() === String(categoryFromRow).toLowerCase().trim()) : null;
    let category = directCatKey ? (CATEGORIES[directCatKey].name || directCatKey) : categoryInfo.category;
    if (isSnapshot) category = 'Other';

    // Upgrade category through resolveTransactionCategory
    category = resolveTransactionCategory({
      category,
      description: cleanedDescription,
      merchant: merchant
    });

    // 6. Anomaly Detection
    let isUnusual = false;
    let unusualReason = '';
    const catRange = CATEGORIES[category]?.typicalDailyRange;
    if (normalizedType === 'expense' && catRange && parsedAmount > catRange[1] * 4 && parsedAmount > 2000) {
      isUnusual = true;
      unusualReason = `Unusual / Needs Review: ₹${parsedAmount.toLocaleString('en-IN')} is unusually high for ${category}`;
      warnings.push(unusualReason);
    }

    // 7. Duplicate Detection
    const matchesExisting = (existingTransactions || []).some(tx => {
      if (!tx || typeof tx !== 'object') return false;
      const dateMatch = tx.date === parsedDate;
      const amtMatch = Math.abs(Number(tx.amount) || 0) === parsedAmount;
      const descMatch = String(tx.description || '').toLowerCase().trim() === cleanedDescription.toLowerCase() ||
                        String(tx.merchant || '').toLowerCase().trim() === merchant.toLowerCase();
      return dateMatch && amtMatch && descMatch;
    });

    const batchKey = `${parsedDate}_${parsedAmount}_${merchant.toLowerCase()}`;
    const isBatchDuplicate = seenInBatch.has(batchKey);
    seenInBatch.add(batchKey);

    const isDuplicate = matchesExisting || isBatchDuplicate;
    if (isDuplicate) {
      warnings.push(isBatchDuplicate ? 'Duplicate entry in statement' : 'Duplicate suspect: already in ledger');
    }

    const normalizedRecord = {
      id: `tx_imported_${Date.now()}_${index}`,
      date: parsedDate,
      description: cleanedDescription,
      merchant: merchant || 'Merchant',
      amount: parsedAmount,
      type: normalizedType,
      category,
      paymentMethod: rawRow.Channel || rawRow.paymentMethod || paymentMethod,
      recurring: categoryInfo.recurring,
      essential: categoryInfo.essential,
      confidence: categoryInfo.confidence,
      source: 'imported',
      isBalanceSnapshot: isSnapshot,
      isUnusual,
      unusualReason
    };

    return {
      index,
      raw: rawRow,
      normalized: normalizedRecord,
      errors,
      warnings,
      isValid: errors.length === 0,
      isDuplicate,
      isBalanceSnapshot: isSnapshot,
      autoRepaired,
      selected: errors.length === 0 && !isDuplicate && !isSnapshot
    };
  });

  return {
    rows: normalizedRows,
    detectedOpeningBalance
  };
}
